// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXjlVAgcwE4UHRyiXZvq3ByFLnz27mqvc',
    appId: '1:308896699883:web:3bc278ed60cceef4b275ae',
    messagingSenderId: '308896699883',
    projectId: 'familyandfriends-space',
    authDomain: 'familyandfriends-space.firebaseapp.com',
    storageBucket: 'familyandfriends-space.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq2Jp7JlGINY9v4J-nFixYPW0ohNDXbME',
    appId: '1:308896699883:android:f02227fe07d50fbcb275ae',
    messagingSenderId: '308896699883',
    projectId: 'familyandfriends-space',
    storageBucket: 'familyandfriends-space.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFTb0l3NxNJ-LRZoMD4vq-KjjhIKe6vyE',
    appId: '1:308896699883:ios:f08edf003a0a3a42b275ae',
    messagingSenderId: '308896699883',
    projectId: 'familyandfriends-space',
    storageBucket: 'familyandfriends-space.firebasestorage.app',
    iosBundleId: 'com.example.familyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFTb0l3NxNJ-LRZoMD4vq-KjjhIKe6vyE',
    appId: '1:308896699883:ios:f08edf003a0a3a42b275ae',
    messagingSenderId: '308896699883',
    projectId: 'familyandfriends-space',
    storageBucket: 'familyandfriends-space.firebasestorage.app',
    iosBundleId: 'com.example.familyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXjlVAgcwE4UHRyiXZvq3ByFLnz27mqvc',
    appId: '1:308896699883:web:c07c42c4c2f15e2db275ae',
    messagingSenderId: '308896699883',
    projectId: 'familyandfriends-space',
    authDomain: 'familyandfriends-space.firebaseapp.com',
    storageBucket: 'familyandfriends-space.firebasestorage.app',
  );
}
